language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

install: "pip install -r requirements_dev.txt"

# command to run tests, e.g. python setup.py test
script:
  - python3.6 $(which pre-commit) run -a
  - python setup.py test
